### ISSUE TITLE
"Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait" not found Sylius 1.9

### ISSUE THREAD

**Issue by Zilus** [Setono/SyliusTrustpilotPlugin#26]
Im following the install instructions, and when traing to diff the migration (or try to clear the cache) I get the folowwing error:

```Fatal error: During class fetch: Uncaught ReflectionException: Class "Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait" not found while loading "Setono\SyliusTrustpilotPlugin\Controller\CustomerController". in /var/www/app/vendor/symfony/config/Resource/ClassExistenceResource.php:181
Stack trace:
#0 [internal function]: Symfony\Component\Config\Resource\ClassExistenceResource::throwOnRequiredClass('Symfony\\Bundle\\...')
#1 /var/www/app/vendor/setono/sylius-trustpilot-plugin/src/Controller/TrustpilotCustomerTrait.php(20): spl_autoload_call('Symfony\\Bundle\\...')
#2 /var/www/app/vendor/composer/ClassLoader.php(444): include('/var/www/app/ve...')
#3 /var/www/app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/app/ve...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Setono\\SyliusTr...')
#5 /var/www/app/vendor/setono/sylius-trustpilot-plugin/src/Controller/CustomerController.php(11): spl_autoload_call('Setono\\SyliusTr...')
#6 /var/www/app/vendor/composer/ClassLoad in /var/www/app/vendor/setono/sylius-trustpilot-plugin/src/Controller/TrustpilotCustomerTrait.php on line 20
```

Reading the file: 
vendor/setono/sylius-trustpilot-plugin/src/Controller/TrustpilotCustomerTrait.php I see it references a not existing trait:

` use Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait;`

Is this plugin not compatible with Sylius 1.9?

**Comment by loevgaard** [comment]
This isn't valid anymore :)
